### ISSUE TITLE
第七章作业

### ISSUE THREAD

**Issue by yuzhou01** [kahowang/sensor-fusion-for-localization-and-mapping#3]
自己电脑上能编译过，最开始时运行roslaunch都每版本，但是后面显示每没有各个坐标系的转换数据。看截图
![2022-03-17 16-22-53 的屏幕截图](https://user-images.githubusercontent.com/96414333/158768120-74235549-0bd4-43d6-9e14-1368b802e220.png)
![2022-03-17 16-23-26 的屏幕截图](https://user-images.githubusercontent.com/96414333/158768136-32de6db1-54e3-4ba3-bdd7-5fa866926db6.png)

**Comment by kahowang** [comment]
My environment is ubutnu18.04 ROS melodic . You worked  in ubutnu20.04 ros neotic,i also try to  test in ubuntu 20.04 environment last month ,but so pity , i failed .  It has some worngs,  one of the wrong is in neotic ,tf is change to tf2. If you slove it ,please tell me. Thanks a lot.

**Comment by Natsu-Akatsuki** [comment]
- In noetic you need to strip any leading / character in frame_id. Unfortunetely, this is a insignificant problem. The key problem you may face is that the SLAM effect could be not consistent with melodic version (have a worse effect...) .We temporarily agree on that idea, the dependency/library that the algorithm depents on is not the same as the melodic...Welcome for any feedback. Thanks.
- noetic版本的话，你需要将frame_id里面的前导符号"/"给去掉。值得注意的是，即使解决了这个问题，你会进一步发现一个更大的坑。怎么出来的定位效果这么奇怪？一点都不靠谱？这边跟作者暂时达成的共识是，算法依赖的库的版本不太同，出来的效果也不一样...你可能还会遇到一个redundant时间戳的问题，然后我们这边经过详细的资料查阅，实际上这个并不是很影响最终的效果。欢迎各种反馈。溜~

**Comment by yuzhou01** [comment]
> 我的环境是 ubutnu18.04 ROS 旋律。你在 ubutnu20.04 ros neotic 工作，我上个月也尝试在 ubuntu 20.04 环境下测试，但很遗憾，我失败了。它有一些磨损，其中一个错误是neotic，tf是更改为tf2。如果你喜欢它，请告诉我。非常感谢。

非常感觉你们出色的工作，之前我也是用的ubuntu18.04，但是编译过程中出现各种问题，后来选择了20.04.编译能过，但运行效果不佳。我这边打算再用18.04尝试一下，如果后续遇到一些问题，希望大佬可以指导下。/抱拳

**Comment by kahowang** [comment]
Thanks for your reply, Welcome for any feedback. Thanks.

**Comment by yuzhou01** [comment]
> Thanks for your reply, Welcome for any feedback. Thanks.

我在自己电脑上重组了18.04试图来解决上述的因系统版本差异带来的错误。但是在安装Sophus库时，总算遇到这些编译错误，在网上也没有找到解决方案,应该是fmt库的问题。不知道你们在安装时，也没有遇到这样的问题，是如何解决的？
![2022-03-22 10-08-23 的屏幕截图](https://user-images.githubusercontent.com/96414333/159393146-0a088346-a890-46ca-8a0c-c1076401e5b1.png)

**Comment by kahowang** [comment]
about the problem with sophus fmt,  you can also see this link https://blog.csdn.net/weixin_41281151/article/details/120904368 多传感器融合定位 第七章 基于滤波的融合方法。You can try this terminal  command 

git clone https://github.com/fmtlib/fmt
cd fmt/
mkdir build
cd build
cmake ..
make
sudo make install		
-------------------------------------------
cd   catkin_ws/src/lidar_localization/cmake/sophus.cmake
-------------------------------------------
#  sophus.cmake
find_package (Sophus REQUIRED)

include_directories(${Sophus_INCLUDE_DIRS})
list(APPEND ALL_TARGET_LIBRARIES ${Sophus_LIBRARIES} fmt)

Hope you can help.Thanks for your reply.

**Comment by yuzhou01** [comment]
> 关于 sophus fmt 的问题，也可以看这个https://blog.csdn.net/weixin_41281151/article/details/120904368传感器定位第七章多关节融合的方法。可以试试这个命令命令
> 
> ## git clone https://github.com/fmtlib/fmt
> cd fmt/
> mkdir build
> cd build
> cmake ..
> make
> sudo make install
> ## cd catkin_ws/src/lidar_localization/cmake/sophus.cmake
> # sophus.cmake
> find_package（需要Sophus）
> 
> 包含目录（${Sophus_INCLUDE_DIRS}） 列表（APPEND ALL_TARGET_LIBRARIES ${So

> 关于 sophus fmt 的问题，也可以看这个https://blog.csdn.net/weixin_41281151/article/details/120904368传感器定位第七章多关节融合的方法。可以试试这个命令
> 
> ## git clone https://github.com/fmtlib/fmt
> cd fmt/
> mkdir build
> cd build
> cmake ..
> make
> sudo make install
> ## cd catkin_ws/src/lidar_localization/cmake/sophus.cmake
> # sophus.cmake
> find_package（需要Sophus）
> 
> 包含目录（${Sophus_INCLUDE_DIRS}） 列表（APPEND ALL_TARGET_LIBRARIES ${Sophus_LIBRARIES} fmt）
> 
> 希望你能帮忙。谢谢你的回复。

非常感谢你的回复，问题已解决，是fmt库版本的问题，用的fmt 8.0.1已编译成功，而fmt最新的库都会报我之前的错。再次感谢你的回复。

**Comment by yuzhou01** [comment]
你好，第七章卡尔曼滤波融合的代码已经跑起来了，非常感谢你的指导。如果我需要跑自己的数据集，这个大概需要如何实现呢，我想在这个基础上做一些改进优化。

**Comment by kahowang** [comment]
You can compare the topic of your own data set to modify, and pay attention to the external parameter, Modify and debug 
according to your own data. Have fun.
